parent_run_name: "backend_logic_reid_association_comparison" # Renamed for clarity

mlflow:
  experiment_name: "Tracking+ReID (Backend Logic - Association Methods)"

environment:
  device: "auto"
  seed: 42

data:
  base_path: "D:/MTMMC"
  weights_base_dir: "weights/reid"
  selected_environment: "factory"
  campus:
    scene_id: "s47"
    camera_ids: ["c01", "c02", "c03", "c05"]
    max_frames_per_camera: -1
  factory:
    scene_id: "s10"
    camera_ids: ["c09", "c12", "c13", "c16"]
    max_frames_per_camera: -1

tracker_params:
  type: "botsort"
  half_precision: False
  per_class: False

reid_params:
  model_type: "clip"
  weights_path: "clip_market1501.pt"
  half_precision: False
  similarity_threshold: 0.65 # Used for cosine/inner_product
  # l2_distance_threshold: 0.9 # Example: if you want to specify for L2. If absent, will derive from similarity_threshold.
  gallery_ema_alpha: 0.9
  refresh_interval_frames: 10
  lost_track_buffer_frames: 200
  main_gallery_prune_interval_frames: 500
  main_gallery_prune_threshold_frames: 400


reid_association_methods_to_compare:
  - "cosine"          # Current method via scipy.spatial.distance.cdist
  - "l2_derived"      # L2 distance via scipy.spatial.distance.cdist, threshold derived from cosine
  - "inner_product"   # Direct dot product (equivalent to cosine for normalized vectors)
  - "faiss_ip"        # FAISS with IndexFlatIP (for max inner product / cosine similarity)
  - "faiss_l2"        # FAISS with IndexFlatL2 (for min L2 distance)


handoff_config:
  min_bbox_overlap_ratio_in_quadrant: 0.40
  homography_data_dir: "homography_data_ml"
  possible_camera_overlaps:
    - ["c09", "c12"]
    - ["c12", "c13"]
    - ["c13", "c16"]
    - ["c01", "c03"]
    - ["c02", "c03"]
    - ["c03", "c05"]
  camera_details:
    "('campus', 'c01')":
      exit_rules:
        - source_exit_quadrant: "upper_right"
          target_cam_id: "c03"
          target_entry_area: "bottom_left"
      homography_matrix_path: "homography_points_c01_scene_s47.npz"
    "('campus', 'c02')":
      exit_rules:
        - source_exit_quadrant: "upper_right"
          target_cam_id: "c05"
          target_entry_area: "upper left"
      homography_matrix_path: "homography_points_c02_scene_s47.npz"
    "('campus', 'c03')":
      exit_rules:
        - source_exit_quadrant: "bottom_left"
          target_cam_id: "c01"
          target_entry_area: "upper_right"
        - source_exit_quadrant: "upper_right"
          target_cam_id: "c05"
          target_entry_area: "upper left"
      homography_matrix_path: "homography_points_c03_scene_s47.npz"
    "('campus', 'c05')":
      exit_rules:
        - source_exit_quadrant: "upper_left"
          target_cam_id: "c02"
          target_entry_area: "upper_right"
        - source_exit_quadrant: "upper_left"
          target_cam_id: "c03"
          target_entry_area: "upper_right"
      homography_matrix_path: "homography_points_c05_scene_s47.npz"
    "('factory', 'c09')":
      exit_rules:
        - source_exit_quadrant: "lower_left"
          target_cam_id: "c13"
          target_entry_area: "upper right"
          notes: "wait; overlap c13/c16 possible"
        - source_exit_quadrant: "lower_right"
          target_cam_id: "c13"
          target_entry_area: "upper right"
          notes: "wait; overlap c13/c16 possible"
      homography_matrix_path: "homography_points_c09_scene_s14.npz"
    "('factory', 'c12')":
      exit_rules:
        - source_exit_quadrant: "upper_left"
          target_cam_id: "c13"
          target_entry_area: "upper left"
          notes: "overlap c13 possible"
        - source_exit_quadrant: "lower_left"
          target_cam_id: "c13"
          target_entry_area: "upper left"
          notes: "overlap c13 possible"
      homography_matrix_path: "homography_points_c12_scene_s14.npz"
    "('factory', 'c13')":
      exit_rules:
        - source_exit_quadrant: "upper_right"
          target_cam_id: "c09"
          target_entry_area: "down"
          notes: "wait; overlap c09 possible"
        - source_exit_quadrant: "lower_right"
          target_cam_id: "c09"
          target_entry_area: "down"
          notes: "wait; overlap c09 possible"
        - source_exit_quadrant: "upper_left"
          target_cam_id: "c12"
          target_entry_area: "upper left"
          notes: "overlap c12 possible"
        - source_exit_quadrant: "lower_left"
          target_cam_id: "c12"
          target_entry_area: "upper left"
          notes: "overlap c12 possible"
      homography_matrix_path: "homography_points_c13_scene_s14.npz"
    "('factory', 'c16')":
      exit_rules: []
      homography_matrix_path: "homography_points_c16_scene_s14.npz"

evaluation:
  person_class_id: 0