# Enhanced Detection Analysis Configuration - Phase 1
# This configuration drives the comprehensive enhanced detection analysis pipeline

# Model Configuration - Either local_model_path OR mlflow_run_id must be set
# mlflow_run_id: "CHANGE_ME_RUN_ID" # Replace with your MLflow Run ID
local_model_path: "checkpoints/7af7b38617994e41adbd761df223cf93/ckpt_best_eval_map_50.pth"

# --- Model Architecture ---
model:
  type: "fasterrcnn"
  backbone_weights: "FasterRCNN_ResNet50_FPN_Weights.DEFAULT"
  num_classes: 2 # person + background
  trainable_backbone_layers: 3

# --- MLflow Configuration ---
mlflow:
  experiment_name: "Enhanced Detection Analysis - Phase 1"

# --- Environment Configuration ---
environment:
  device: "auto"  # auto, cpu, cuda, cuda:0, etc.
  seed: 42

# --- Data Configuration ---
data:
  # IMPORTANT: Update this path to point to your MTMMC dataset
  # base_path: "/Volumes/HDD/MTMMC"
  base_path: "D:/MTMMC"
  
  # Scenes and cameras to analyze
  scenes_to_include:
    - scene_id: "s10"
      camera_ids: ["c09", "c12", "c13", "c16"]
    - scene_id: "s47"
      camera_ids: ["c01", "c02", "c03", "c05"]

  # Data subsetting for faster development/debugging
  use_data_subset: false
  data_subset_fraction: 1.0

  # Train/Val split (analysis runs on validation set)
  val_split_ratio: 0.2
  num_workers: 2

# --- Enhanced Analysis Configuration ---
analysis:
  # Output directory for all analysis results
  output_dir: "outputs/enhanced_detection_analysis"
  
  # Frame sampling and processing
  max_frames: -1        # -1 for all frames, or specify limit for testing
  sample_rate: 1        # Process every Nth frame (1 = all frames)
  max_frames_comparison: 100  # Max frames for cross-model comparison
  
  # Detection parameters
  iou_threshold: 0.5    # IoU threshold for matching detections to ground truth
  confidence_threshold: 0.5  # Minimum confidence for considering detections
  
  # Scene analysis thresholds
  scene_analysis:
    brightness_thresholds:
      day: 120
      night: 80
    density_thresholds:
      low: 2
      high: 8
    size_thresholds:
      small_area: 1024    # 32x32 pixels
      large_area: 9216    # 96x96 pixels
  
  # Visualization parameters
  visualization:
    colors:
      ground_truth: [0, 255, 0]     # Green
      prediction: [255, 0, 0]       # Red
      missed_detection: [0, 0, 255] # Blue
    font_scale: 0.8
    thickness: 2
    generate_heatmaps: true
    generate_failure_examples: true
    max_examples_per_category: 20

# --- Cross-Model Comparison Configuration ---
cross_model_analysis:
  enabled: false  # Set to true to enable cross-model comparison
  
  # Model configurations for comparison (example)
  models:
    fasterrcnn:
      type: "fasterrcnn"
      weights_path: "DEFAULT"
      confidence_threshold: 0.5
      person_class_id: 1
    # Add more models as needed:
    # yolo:
    #   type: "yolo"
    #   weights_path: "yolov8n.pt"
    #   confidence_threshold: 0.5
    #   person_class_id: 0

# --- Advanced Metrics Configuration ---
advanced_metrics:
  # mAP calculation settings
  iou_thresholds: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
  
  # Confidence analysis
  confidence_bins: 10
  
  # Performance profiling
  enable_timing: true
  enable_memory_profiling: false  # Set to true for memory usage analysis

# --- Automated Reporting Configuration ---
reporting:
  # Report generation settings
  generate_html_report: true
  generate_executive_dashboard: true
  generate_trend_analysis: true
  
  # Alert thresholds
  alert_thresholds:
    f1_score_min: 0.7
    precision_min: 0.75
    recall_min: 0.75
    processing_time_max: 0.1  # 100ms
    success_rate_min: 0.95
  
  # Report customization
  include_visualizations: true
  include_recommendations: true
  max_visualizations: 20

# --- Output Format Configuration ---
output_formats:
  save_json_reports: true
  save_csv_metrics: true
  save_visualizations: true
  compress_outputs: false  # Set to true to compress output directory