run_name: "fasterrcnn_factory_s10_100frames" # Example: descriptive run name

environment:
  device: "auto" # Options: "auto", "cuda:0", "mps", "cpu"

data:
  base_path: "/Volumes/HDD/MTMMC"
  selected_environment: "factory" # Options: "factory", "campus"

# --- Environment Specific Settings ---
  # Note: The actual scene path will be constructed as base_path/train/train/scene_id
  campus:
    scene_id: "s47"
    camera_ids: [ "c01", "c02", "c03", "c05" ]
    max_frames_per_camera: 100  # Or -1

  factory:
    scene_id: "s10"
    camera_ids: [ "c09", "c12", "c13", "c16" ]
    max_frames_per_camera: 100   # Or -1

model:
  type: "fasterrcnn"  # Options: "yolo", "rtdetr", "fasterrcnn", "rfdetr" (Match keys in strategies.py)
  weights_path: "fasterrcnn_resnet50_fpn"  # Options: "yolov11x.pt", "rtdetr-x.pt", "rfdetr_l", "fasterrcnn_resnet50_fpn"
  confidence_threshold: 0.5
  person_class_id: 1  # COCO=0, torchvision=1
  input_width: 640

tracker:
  history_length: 400

mlflow:
  experiment_name: "Person Detection Comparison MTMMC"

evaluation:
  iou_threshold: 0.5

logging_metrics:
  - avg_inference_time_ms_per_frame
  - total_person_detections
  - avg_detections_per_frame
  - processing_fps