parent_run_name: "mtmmc_reid_comparison"

mlflow:
  experiment_name: "Re-ID Models Comparison - Query/Gallery"

environment:
  device: "auto" # Options: "auto", "cuda:0", "mps", "cpu"
  seed: 42

data:
  base_path: "D:/MTMMC" # Adjust to your MTMMC dataset path
  # base_path: "/Volumes/HDD/MTMMC"
  weights_base_dir: "weights/reid"

  # --- Evaluation Split ---
  split_type: "val" # Options: "train", "val"

  # --- Environment / Scene Selection ---
  selected_environment: "factory" # Options: "factory", "campus"

  # --- Scene Specific Settings ---
  campus:
    scene_id: "s37"
    scene_annotation_file: "s37.json" # JSON file for this scene in data.base_path/split/data.split_type/
    camera_ids: ["c01", "c02", "c03", "c05"]
    frame_sample_rate: 5
    max_crops_per_id_per_cam: -1
    query_cameras: ["c01", "c03"]
    gallery_cameras: ["c02", "c05"]

  factory:
    scene_id: "s14"
    scene_annotation_file: "s14.json" # JSON file for this scene in data.base_path/split/data.split_type/
    camera_ids: ["c09", "c12", "c13", "c16"]
    frame_sample_rate: 5
    max_crops_per_id_per_cam: -1
    query_cameras: ["c09", "c12"]
    gallery_cameras: ["c13", "c16"]

evaluation:
  distance_metric: "cosine" # "cosine" or "euclidean"

# --- Re-ID Models to Run (as Child Runs) ---
models_to_run:
  # --- CLIP ViT Models ---
  - model:
      model_type: "clip_vit_b16"  # More specific type based on filename
      weights_path: "Duke_clipreid_ViT-B-16_60.pth"
      input_size: [224, 224]      # Assuming standard ViT/CLIP input
      feature_dim: 512           # Keeping your value
  - model:
      model_type: "clip_vit_b16"
      weights_path: "Market1501_clipreid_ViT-B-16_60.pth"
      input_size: [224, 224]
      feature_dim: 512

  # --- LMBN Models ---
  - model:
      model_type: "lmbn_n"
      weights_path: "lmbn_n_market.pth"
      input_size: [256, 128]
      feature_dim: 512
  - model:
      model_type: "lmbn_n"
      weights_path: "lmbn_n_duke.pth"
      input_size: [256, 128]
      feature_dim: 512

  # --- OSNet Models ---
  - model:
      model_type: "osnet_ibn_x1_0"
      # Using full name for clarity, adjust if your loading logic simplifies this
      weights_path: "osnet_ibn_x1_0_msmt17_combineall_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip_jitter.pth"
      input_size: [256, 128]
      feature_dim: 512
  - model:
      model_type: "osnet_ain_x1_0"
      weights_path: "osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth"
      input_size: [256, 128]
      feature_dim: 512
  - model:
      model_type: "osnet_x1_0"
      weights_path: "osnet_x1_0_msmt17_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth"
      input_size: [256, 128]
      feature_dim: 512

  # --- MLFN Models ---
  - model:
      model_type: "mlfn"
      weights_path: "mlfn_market_xent.pth" # Added _xent
      input_size: [256, 128]
      feature_dim: 512
  - model:
      model_type: "mlfn"
      weights_path: "mlfn_duke_xent.pth"   # Added _xent
      input_size: [256, 128]
      feature_dim: 512

  # --- HACNN Models ---
  - model:
      model_type: "hacnn"
      weights_path: "hacnn_market_xent.pth" # Added _xent
      input_size: [160, 64]
      feature_dim: 512
  - model:
      model_type: "hacnn"
      weights_path: "hacnn_duke_xent.pth"   # Added _xent
      input_size: [160, 64]
      feature_dim: 512

  # --- MobileNetV2 Models ---
  - model:
      model_type: "mobilenetv2_x1_4" # Using your notation
      weights_path: "mobilenetv2_1dot4_market.pth" # Matched filename (1dot4)
      input_size: [256, 128]
      feature_dim: 1792
  - model:
      model_type: "mobilenetv2_x1_4"
      weights_path: "mobilenetv2_1dot4_duke.pth"   # Matched filename (1dot4)
      input_size: [256, 128]
      feature_dim: 1792

  # --- ResNet50 Models ---
  - model:
      # Type could be 'resnet50' or 'resnet50_fc512' depending on loading logic
      model_type: "resnet50_fc512"
      weights_path: "resnet50_fc512_msmt_xent.pth" # Matched filename
      input_size: [256, 128]
      feature_dim: 512
  - model:
      model_type: "resnet50_fc512"
      weights_path: "resnet50_fc512_market_xent.pth" # Matched filename
      input_size: [256, 128]
      feature_dim: 512