run_name: "fasterrcnn_factory_s10_single"

mlflow:
  experiment_name: "Person Detection Single Runs"

environment:
  device: "auto" # Options: "auto", "cuda:0", "mps", "cpu"
  seed: 42

data:
#  base_path: "/Volumes/HDD/MTMMC"
  base_path: "D:/MTMMC"
  selected_environment: "factory" # Options: "factory", "campus"

# --- Environment Specific Settings ---
  # Note: The actual scene path will be constructed as base_path/train/train/scene_id
  campus:
    scene_id: "s47"
    camera_ids: [ "c01", "c02", "c03", "c05" ]
    max_frames_per_camera: 100 # Or -1

  factory:
    scene_id: "s10"
    camera_ids: [ "c09", "c12", "c13", "c16" ]
    max_frames_per_camera: 100 # Or -1

model:
  # --- Model Specific Settings ---
  model_name: "fasterrcnn_resnet50" # Added for clarity, can be used for tagging etc.
  type: "fasterrcnn"  # Options: "yolo", "rtdetr", "fasterrcnn", "rfdetr"
  weights_path: "FasterRCNN_ResNet50_FPN_Weights.DEFAULT"
  confidence_threshold: 0.5
  person_class_id: 1  # COCO=0, torchvision=1
  input_width: 640
