parent_run_name: "mtmmc_tracking_reid_comparison"

mlflow:
  experiment_name: "Tracking+ReID Comparison (BoxMOT)"

environment:
  device: "auto" # Options: "auto", "cuda:0", "mps", "cpu"
  seed: 42

data:

  base_path: "D:/MTMMC"
  # base_path: "/Volumes/HDD/MTMMC"

  weights_base_dir: "weights/reid"

  # --- Environment / Scene Selection ---
  selected_environment: "factory" # Options: "factory", "campus"

  # --- Scene Specific Settings (Similar to Detection Config) ---
  campus:
    scene_id: "s47"
    camera_ids: [ "c01", "c02", "c03", "c05" ]
    max_frames_per_camera: 100 # Or -1

  factory:
    scene_id: "s10"
    camera_ids: [ "c09", "c12", "c13", "c16" ]
    max_frames_per_camera: 100 # Or -1

# --- Trackers to Run ---
trackers_to_run:
  - "deepocsort"
  - "strongsort"
  - "botsort"
  - "boosttrack"
  - "imprassoc"

# --- Re-ID Models to Associate with Trackers ---
reid_models_to_associate:
  # --- CLIP ViT Models ---
  - model_type: "clip"
    weights_path: "clip_duke.pt"
  - model_type: "clip"
    weights_path: "clip_market1501.pt"

  # --- LMBN Models ---
  - model_type: "lmbn_n"
    weights_path: "lmbn_n_market.pt"
  - model_type: "lmbn_n"
    weights_path: "lmbn_n_duke.pt"

  # --- OSNet Models ---
  - model_type: "osnet_ibn_x1_0"
    weights_path: "osnet_ibn_x1_0_msmt17.pt"
  - model_type: "osnet_ain_x1_0"
    weights_path: "osnet_ain_x1_0_msmt17.pt"
  - model_type: "osnet_x1_0"
    weights_path: "osnet_x1_0_msmt17.pt"

  # --- MLFN Models ---
  - model_type: "mlfn"
    weights_path: "mlfn_market1501.pt"
  - model_type: "mlfn"
    weights_path: "mlfn_dukemtmcreid.pt"

  # --- HACNN Models ---
  - model_type: "hacnn"
    weights_path: "hacnn_market1501.pt"
  - model_type: "hacnn"
    weights_path: "hacnn_dukemtmcreid.pt"

  # --- MobileNetV2 Models ---
  - model_type: "mobilenetv2_x1_4"
    weights_path: "mobilenetv2_x1_4_market1501.pt"
  - model_type: "mobilenetv2_x1_4"
    weights_path: "mobilenetv2_x1_4_dukemtmcreid.pt"

  # --- ResNet50 Models ---
  - model_type: "resnet50"
    weights_path: "resnet50_fc512_msmt17.pt"
  - model_type: "resnet50"
    weights_path: "resnet50_fc512_market1501.pt"

evaluation:
  person_class_id: 0
