#!/usr/bin/env python3
"""
Re-ID Analysis Runner

This script runs the Re-ID analysis pipeline which:
1. Uses ground truth detection boxes to isolate Re-ID performance
2. Analyzes multiple Re-ID models for failure patterns
3. Collects 1-per-person-ID Re-ID failures with comprehensive metadata
4. Generates dual-color visualizations for Re-ID analysis
5. Correlates failures with environmental conditions
6. Provides actionable insights for Re-ID model improvements

Usage:
    python src/run_reid_analysis.py [--config CONFIG_PATH] [--device DEVICE]

Example:
    python src/run_reid_analysis.py --config configs/reid_analysis_config.yaml --device cuda:0

Author: Generated by Claude Code
"""

import argparse
import logging
import sys
import traceback
from pathlib import Path
from typing import Dict, Any

import torch
import mlflow

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from src.utils.config_loader import load_config
from src.utils.logging_utils import setup_logging
from src.utils.reproducibility import set_seed
from src.utils.mlflow_utils import setup_mlflow
from src.pipelines.phase2_reid_analysis import run_phase2_reid_analysis

logger = logging.getLogger(__name__)

def parse_arguments() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Run Re-ID Analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Run with default configuration
    python src/run_reid_analysis.py
    
    # Run with custom configuration
    python src/run_reid_analysis.py --config configs/reid_analysis_config.yaml
    
    # Run with specific device
    python src/run_reid_analysis.py --device cuda:0
    
    # Run with CPU only
    python src/run_reid_analysis.py --device cpu
        """
    )
    
    parser.add_argument(
        "--config",
        type=str,
        default="configs/reid_analysis_config.yaml",
        help="Path to configuration file (default: configs/reid_analysis_config.yaml)"
    )
    
    parser.add_argument(
        "--device",
        type=str,
        default=None,
        help="Device to use (e.g., 'cuda:0', 'cpu'). If not specified, uses config setting."
    )
    
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Override output directory from config"
    )
    
    parser.add_argument(
        "--models",
        type=str,
        nargs="+",
        default=None,
        help="Specific Re-ID models to analyze (subset of config models)"
    )
    
    parser.add_argument(
        "--scenes",
        type=str,
        nargs="+",
        default=None,
        help="Specific scenes to analyze (e.g., s10 s47)"
    )
    
    parser.add_argument(
        "--cameras",
        type=str,
        nargs="+",
        default=None,
        help="Specific cameras to analyze (e.g., c09 c12)"
    )
    
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug mode with verbose logging"
    )
    
    parser.add_argument(
        "--no-mlflow",
        action="store_true",
        help="Disable MLflow logging"
    )
    
    parser.add_argument(
        "--quick",
        action="store_true",
        help="Quick analysis mode (reduced dataset, fewer models)"
    )
    
    return parser.parse_args()

def setup_device(config: Dict[str, Any], device_override: str = None) -> torch.device:
    """Setup and validate device configuration."""
    if device_override:
        device_str = device_override
    else:
        device_str = config.get("environment", {}).get("device", "cpu")
    
    # Validate device availability
    if device_str.startswith("cuda"):
        if not torch.cuda.is_available():
            logger.warning(f"CUDA not available, falling back to CPU")
            device_str = "cpu"
        else:
            # Check if specific GPU is available
            if ":" in device_str:
                gpu_id = int(device_str.split(":")[1])
                if gpu_id >= torch.cuda.device_count():
                    logger.warning(f"GPU {gpu_id} not available, using cuda:0")
                    device_str = "cuda:0"
    
    device = torch.device(device_str)
    logger.info(f"Using device: {device}")
    
    return device

def apply_command_line_overrides(config: Dict[str, Any], args: argparse.Namespace) -> None:
    """Apply command line argument overrides to configuration."""
    
    # Override output directory
    if args.output_dir:
        config.setdefault("analysis", {})["output_dir"] = args.output_dir
    
    # Override Re-ID models
    if args.models:
        if "reid_models" in config:
            config["reid_models"] = [
                model for model in config["reid_models"] 
                if model["name"] in args.models
            ]
            logger.info(f"Analyzing subset of models: {args.models}")
    
    # Override scenes
    if args.scenes:
        if "data" in config and "scenes_to_include" in config["data"]:
            config["data"]["scenes_to_include"] = [
                scene for scene in config["data"]["scenes_to_include"]
                if scene["scene_id"] in args.scenes
            ]
            logger.info(f"Analyzing subset of scenes: {args.scenes}")
    
    # Override cameras
    if args.cameras:
        if "data" in config and "scenes_to_include" in config["data"]:
            for scene in config["data"]["scenes_to_include"]:
                scene["camera_ids"] = [
                    cam for cam in scene["camera_ids"] 
                    if cam in args.cameras
                ]
            logger.info(f"Analyzing subset of cameras: {args.cameras}")
    
    # Quick mode adjustments
    if args.quick:
        config.setdefault("analysis", {}).update({
            "max_persons_per_scene": 50,
            "min_track_length": 2,
            "generate_feature_space_plots": False,
            "perform_dimensionality_reduction": False
        })
        
        # Use subset of data
        config.setdefault("data", {}).update({
            "use_data_subset": True,
            "data_subset_fraction": 0.1
        })
        
        logger.info("Quick mode enabled - using reduced dataset and features")
    
    # Debug mode
    if args.debug:
        config.setdefault("analysis", {})["debug_mode"] = True
        config.setdefault("logging", {})["level"] = "DEBUG"

def validate_configuration(config: Dict[str, Any]) -> None:
    """Validate configuration before running analysis."""
    
    # Validate data configuration
    if "data" not in config:
        raise ValueError("Data configuration is required")
    
    data_config = config["data"]
    base_path = Path(data_config.get("base_path", ""))
    
    if not base_path.exists():
        raise ValueError(f"Dataset base path does not exist: {base_path}")
    
    # Validate Re-ID models configuration
    if "reid_models" not in config or not config["reid_models"]:
        raise ValueError("At least one Re-ID model must be configured")
    
    # Validate Re-ID model weights
    for model_config in config["reid_models"]:
        if "weights_path" in model_config:
            weights_path = Path(model_config["weights_path"])
            if not weights_path.exists():
                logger.warning(f"Re-ID model weights not found: {weights_path}")
    
    # Validate analysis configuration
    analysis_config = config.get("analysis", {})
    output_dir = Path(analysis_config.get("output_dir", "outputs/phase2_reid_analysis"))
    
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        raise ValueError(f"Cannot create output directory {output_dir}: {e}")
    
    logger.info("Configuration validation passed")

def main() -> None:
    """Main function to run Phase 2 Re-ID analysis."""
    try:
        # Parse arguments
        args = parse_arguments()
        
        # Load configuration
        logger.info(f"Loading configuration from: {args.config}")
        config = load_config(args.config)
        
        # Apply command line overrides
        apply_command_line_overrides(config, args)
        
        # Setup logging
        logging_config = config.get("logging", {})
        if args.debug:
            logging_config["level"] = "DEBUG"
        setup_logging(logging_config)
        
        # Setup reproducibility
        seed = config.get("environment", {}).get("seed", 42)
        set_seed(seed)
        logger.info(f"Set random seed to: {seed}")
        
        # Setup device
        device = setup_device(config, args.device)
        
        # Validate configuration
        validate_configuration(config)
        
        # Setup MLflow (if not disabled)
        if not args.no_mlflow:
            mlflow_config = config.get("mlflow", {})
            setup_mlflow(mlflow_config)
            
            # Start MLflow run
            experiment_name = mlflow_config.get("experiment_name", "Phase 2 Re-ID Analysis")
            mlflow.set_experiment(experiment_name)
            
            with mlflow.start_run():
                # Log configuration parameters
                mlflow.log_params({
                    "config_file": args.config,
                    "device": str(device),
                    "num_reid_models": len(config.get("reid_models", [])),
                    "num_scenes": len(config.get("data", {}).get("scenes_to_include", [])),
                    "seed": seed,
                    "quick_mode": args.quick,
                    "debug_mode": args.debug
                })
                
                # Log analysis parameters
                analysis_params = config.get("analysis", {})
                mlflow.log_params({
                    f"analysis_{k}": v for k, v in analysis_params.items()
                    if isinstance(v, (int, float, str, bool))
                })
                
                # Run analysis
                logger.info("=== Starting Phase 2 Re-ID Analysis ===")
                run_phase2_reid_analysis(config, device)
                
                # Log success
                mlflow.log_metric("analysis_status", 1.0)
                logger.info("=== Phase 2 Re-ID Analysis Complete (Status: SUCCESS) ===")
        else:
            # Run without MLflow
            logger.info("=== Starting Phase 2 Re-ID Analysis (No MLflow) ===")
            run_phase2_reid_analysis(config, device)
            logger.info("=== Phase 2 Re-ID Analysis Complete (Status: SUCCESS) ===")
            
    except KeyboardInterrupt:
        logger.info("Analysis interrupted by user")
        sys.exit(1)
    except Exception as e:
        logger.critical(f"Phase 2 Re-ID analysis failed: {str(e)}")
        logger.critical(f"Traceback: {traceback.format_exc()}")
        
        # Log failure to MLflow if enabled
        if not args.no_mlflow:
            try:
                mlflow.log_metric("analysis_status", 0.0)
                mlflow.log_text(str(e), "error_message.txt")
                mlflow.log_text(traceback.format_exc(), "error_traceback.txt")
            except:
                pass
        
        logger.info("=== Phase 2 Re-ID Analysis Complete (Status: FAILED) ===")
        sys.exit(1)

if __name__ == "__main__":
    main()